### ISSUE TITLE
Add License?

### ISSUE THREAD

**Issue by benjaminpjones** [psalaets/ogs-move-timing#1]
This extension seems really cool, and it's awesome you've made the source code public!  Would you consider adding a license to the project?

> Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

[GitHub: Licensing a Repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

**Comment by psalaets** [comment]
Added a license (mit)

**Comment by benjaminpjones** [comment]
Thanks!
